locations:
  # FORMAT:: worldName:x:y:z:yaw:pitch
  lobby: 'world:-57:93:-263:0.0:0.0'
  # FORMAT :: Same as Team Spawns __ NOTE: The final 0 represents yaw, which doesn't apply to item entities
  snowballs: 'world:-67.5:82:-263:-46.5:-263:0'
  spawns:
    # FORMAT:: worldName:x1:y1:z1:x2:z2:yaw
    red: 'world:-46.5:82:-246.5:-67.5:-246.5:180'
    blue: 'world:-46.5:82:-279.5:-67.5:-279.5:0'
  space:
    # FORMAT:: worldName:x1:y1:z1:x2:y2:z2
    red: 'world:-44:81:-244:-70:84:-263'
    blue: 'world:-71:81:-282:-44:84:-263'
commands:
  victory:
    - 'give {player} diamond 4'